name: The Minnesota Dance Report
favicon: null
layout_spectrum: 0.95786
typography_spectrum: 0.09445
title: News from the Minnesota dance scene
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.5
  lightness: 0.22294977540150285
  saturation: 0.5
  rhythmicContrast: 0.75
purpose: []
