analytics: {}
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.283783
  lightness: 0.222949
  rhythmicContrast: 0
  saturation: 0
cta: {}
layout_spectrum: 0.95786
name: The Minnesota Dance Report
opengraph: {}
purpose: []
typography_spectrum: 0.09445
