analytics: {}
color:
  brandColors:
    - '#C0B890'
    - '#000000'
    - '#A09878'
    - '#000000'
    - '#000000'
  brandStrength: 0
  lightness: 1
  rhythmicContrast: 0
  saturation: 0.451576
cta: {}
layout_spectrum: 0.95786
name: The Minnesota Dance Report
opengraph: {}
purpose: []
typography_spectrum: 0.09445
